# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11HRcVnCKOLI-G7NjK_60YYqoah-Uf6yE
"""

def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def mul(a,b):
    return a*b

def div(a, b):
    if b != 0:
        return a / b
    else:
        return "Cannot divide by zero"